---
   - name: Atualiza a cache (equivalente a apt update)
     apt:
       update_cache: true
       cache_valid_time: 3600

   - name: "Atualiza o sistema operativo"
     apt:
       upgrade: safe

   - name: "Instalar as dependencias necessária ao programa leantime"
     apt:
       pkg:
       - mc
       - screen
       - git
       - apache2
       - mysql-server
       - php
       - php-mysql
       - php-ldap
       - php-cli
       - php-soap
       - php-json
       - graphviz
       - php-xml
       - php-gd
       - php-zip
       - libapache2-mod-php
       - php-dev
       - libmcrypt-dev
       - gcc
       - make
       - autoconf
       - libc-dev
       - pkg-config
       - pwgen
       - curl
       - unzip
       - zip
       - php-mbstring
       - expect
       - net-tools
       - python3-mysqldb
       - python3-apt
       - python3-pycurl

   # Fonte de inspiração: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/service_module.html
   - name: "Instala o serviço apache2 no arranque do sistema"
     service:
       name: apache2
       state: started
       enabled: true

   # Fonte: https://www.mydailytutorials.com/using-ansible-find-module-search-filesfolder
   - name: "Rotina Auxiliar: Procura o caminho do ficheiro php.ini do servidor apache2"
     find:
       paths: /etc
       patterns: "php.ini"
       recurse: true
     register: caminho_php_ini

   # Fonte: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html
   - name: "Ativa várias opções no ficheiro php.ini, utilizando o módulo lineinfile."
     ansible.builtin.lineinfile:
       path: "{{ caminho_php_ini.files[0].path }}"
       regexp: "{{ item.regexp  }}"
       line: "{{ item.line }}"
     with_items:
       - regexp: "^file_uploads"
         line: "file_uploads = 1"
       - regexp: "^upload_max_filesize"
         line: "upload_max_filesize = 1G"
       - regexp: "^max_file_uploads"
         line: "max_file_uploads = 20"
       - regexp: "^post_max_size"
         line: "post_max_size = 2G"
       - regexp: "^memory_limit"
         line: "memory_limit = 2G"
       - regexp: "^max_input_time"
         line: "max_input_time = 3600"

   # Fonte: https://docs.ansible.com/ansible/2.7/modules/file_module.html
   - name: Cria a directoria temporária leantime e a directoria de apache leantime
     file:
       path: "{{ item.path }}"
       state: directory
       mode: 0755
       owner: www-data
       group: www-data
     with_items:
       - path: "/tmp/leantime"
       - path: "/var/www/leantime"
