---
   - name: Atualiza a cache (equivalente a apt update)
     apt:
       update_cache: true
       cache_valid_time: 3600

   - name: "Atualiza o sistema operativo"
     apt:
       upgrade: safe

   - name: "Instalar as dependencias necessária ao programa leantime"
     apt:
       pkg:
       - mc
       - screen
       - git
       - apache2
       - mysql-server
       - php
       - php-mysql
       - php-ldap
       - php-cli
       - php-soap
       - php-json
       - graphviz
       - php-xml
       - php-gd
       - php-zip
       - libapache2-mod-php
       - php-dev
       - libmcrypt-dev
       - gcc
       - make
       - autoconf
       - libc-dev
       - pkg-config
       - pwgen
       - curl
       - unzip
       - zip
       - php-mbstring
       - expect
       - net-tools
       - python3-mysqldb
       - python3-apt
       - python3-pycurl

   # Fonte de inspiração: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/service_module.html
   - name: "Instala o serviço apache2 no arranque do sistema"
     service:
       name: apache2
       state: started
       enabled: true
