---
# Tutorial de inspiração para a infraestrutura conduzida por teste no site
# https://www.adictosaltrabajo.com/2020/05/08/ansible-testing-using-molecule-with-ansible-as-verifier/

- name: "Infraestrutura conduzida por testes"
  hosts: all
  gather_facts: false
  become: true

  tasks:
  - name: "Simulação: Atualizar a cache do sistema"
    apt:
      update_cache: true
      cache_valid_time: 3600
    check_mode: true
    register: estado

  - name: "teste: a cache encontra-se actualizada?"
    assert:
      that:
      - not estado.changed
      success_msg: "SUCESSO: A cache está atualizada"
      fail_msg: "ERRO: Existem actualizações pendentes"
