---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true
provisioner:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint

scenario:
  test_sequence:
  - dependency
  - lint
  - cleanup
  - destroy
  - syntax
  - create
  - prepare
  - converge
  - idempotence
  - verify
  - cleanup
  - destroy

verifier:
  name: ansible
